version: '2'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
            - "8088:8088"
        volumes:
            - ./code:/var/www/html/
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/fastcgi.conf:/etc/nginx/fastcgi.conf
            - ./conf/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: seme_webstack_php:latest
        volumes:
            - ./conf/php.ini:/usr/local/etc/php/php.ini
            - ./code:/var/www/html/
            - ./conf/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
